### ISSUE TITLE
MeCab の Tarball のダウンロード先

### ISSUE THREAD

**Issue by sugryo** [groonga/heroku-groonga-builder#6]
前は、googlecode.com だったのが、Google Code が廃止になったため、
現在は、GoogleDrive に、Tarball が置かれているようなのだが、SSL証明書の問題でダウンロードできていない。
なので、現在私が管理している、pecily.com に Mecab の Tarball をおいてビルドしている。

**Comment by kenhys** [comment]
```
curl --silent --location --fail --output mecab-0.996.tar.gz 'https://drive.google.com/uc?export=download&id=0B4y35FiV1wh7cENtOXlicTFaRUE'
```

とかでいけるんじゃないかと思いました。(環境によるのかな)

**Comment by sugryo** [comment]
@kenhys ありがとうございます。動きました！(私の環境 MacOSX では動きませんでしたが、Heroku では使えるようです。)
これに変更します。
